root: /Users/nanaduah/Desktop/projects.nosync/forkin/src/apis
# python_version: 3.9
routes:
  - path: customer/getCustomer
    url: /api/customers/<country>
    method: GET
    handler: handler.handler
  # - path: hello/hello
  #   url: /hello/<name:path>
  #   method: GET
  #   handler: handler.handler
  #   # venv: hello/.venv

  # - path: hello
  #   url: /api/gif/<id:int>
  #   method: GET
  #   handler: gif.handler
  #   # venv: hello/.venv

  # - path: pickup/createPickup
  #   url: /api/pickups<clientId:path>/<city:path>
  #   method: POST
  #   handler: handler.handler
  # python_version: 3.9

table:
  name: forkin-table-33
  region: us-central-1
  stream:
    view_type: NEW_AND_OLD_IMAGES
    batch_size: 100
    bindings:
      - path: customer/getCustomer
        handler: handler.handler
  key:
    - pk: pk
      type: S
    - sk: sk
      type: S
  indexes:
    - name: GSI1
      key:
        - pk: gsi1_pk
          type: S
        - sk: gsi1_sk
          type: S

cron:
  - path: customer/getCustomer
    handler: handler.handler
    interval: 1m
